### PR TITLE
Example of working with projects

### PR DESCRIPTION
**Pull request by stucka**

### CODE REVIEW

**Comment by palewire** [comment]
I like the idea of this snippet, but I think it might be a little too specific for this page. What do you think of trimming it down a bit and slipped the core of into the undocumented ``pages`` attribute? http://python-documentcloud.readthedocs.io/en/latest/documents.html#document_obj.pages

**Comment by stucka** [comment]
Anything you want to do is fine by me, whether it's rewrite, reject, ridicule or relocate. =) Let me know if you want me to do it or you do it.

**Comment by palewire** [comment]
I think breaking out the final part and then using it to document the ``pages`` method on the Documents page would be a great start. I'd love to have examples for more of those methods showing what they output, and your snippet would be a great start.

**Comment by palewire** [comment]
Since this has unresolved conflicts and is a bit stale I'm going to close it.

**Pull request closed without merging**
